name: Upload IPA to App Store

on:
  workflow_dispatch: # تشغيل يدوي بضغطة زر

jobs:
  upload_to_apple:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare Apple Private Key
        run: |
          # تجهيز المجلد الرسمي الذي تبحث فيه أدوات آبل تلقائياً عن المفاتيح
          mkdir -p ~/.appstoreconnect/private_keys
          echo "${{ secrets.APPLE_PRIVATE_KEY }}" > ~/.appstoreconnect/private_keys/AuthKey_TD923SJ934.p8

      - name: Upload IPA via Native altool
        run: |
          # استخدام أداة آبل الأصلية لرفع التطبيقات مباشرة بدون أي وسيط جافا
          xcrun altool --upload-app \
            -f "./App.ipa" \
            -t ios \
            --apiKey "TD923SJ934" \
            --apiIssuer "6f8de379-0671-4294-b5b8-0a41c4099020"
